server:
  port: 8083

spring:
  application:
    name: barcode-service

services:
  product:
    url: ${SERVICES_PRODUCT_URL:http://localhost:8081}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
